services:
  - type: web
    name: cs2-mini-app
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    # startCommand удалите - пусть использует Procfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
